### ISSUE TITLE
Why missing popular SIGTRAP signal?

### ISSUE THREAD

**Issue by r-plus** [IBM-Swift/BlueSignals#1]
`SIGTRAP` will raise often in Swift(e.g. nil unwrap).
Why missing in Signal enum?

**Comment by billabt** [comment]
Handling **SIGTRAP** in your app would hide bugs (e.g. your nil unwrap) and is not really good programming practice.  This is why it was left out of the framework.  However, should you still desire to do this, the _Signals_ framework will allow you to do so by creating a _USER-DEFINED_ signal.  For example:
```
import Signals

let mySignal = Signals.Signal.user(SIGTRAP)

Signals.trap(signal: mySignal) { signal in

	print("Received signal \(signal)")
}
```

**Comment by r-plus** [comment]
Thanks for your answer, I understood and agree your policy.

BTW, We will trap some signals to do termination processing then `exit` with signal value.
In that case bugs would not hide, isn't it?

**Comment by billabt** [comment]
Not if you're trapping SIGTRAP. If you get this signal, I'd advise just letting the program terminate. You'll then be able to examine the dump and if it's a programming error, you'll be able to find it almost immediately. For other signals, your strategy will work just fine. But for SIGTRAP, the cause is _almost always_ the result of a programming error and you'll end up hiding the cause of it. To then be able to find it, you'll need to remove the trap handler and then hopefully, be able to reproduce it again. For edge case and obscure cases this will be a frustrating endeavor. By not trapping SIGTRAP you'll be able to pinpoint the location of the error the first time it happens.

**Comment by r-plus** [comment]
In iOS(actual device) environment, `dump` means ips(crash report) file? If so, we will lost opportunity to get it, but still able to get stack trace.
Additionally if we execute with lldb(in Xcode scheme configuration), lldb break execution at pinpoint line when catch the signal even if trap that signal in app(ignored our registered handler).
So I thinking we will not frustrating by trapping SIGTRAP.

Lastly again, I agree your policy about this. I understood BlueSignals is cross platform. core dump is useful for find a programming error :)
